[platformio]
default_envs = uwb_sender
src_dir = esp32/src

[env]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps =
    https://github.com/thotro/arduino-dw1000.git#v0.9
extra_scripts =
    pre:esp32/scripts/patch_dw1000_esp32.py

[env:uwb_sender]
build_src_filter =
    -<*>
    +<uwb_sender/>

[env:uwb_receiver]
build_src_filter =
    -<*>
    +<uwb_receiver/>
